include: package:flutter_lints/flutter.yaml

linter:

  rules:
     avoid_print: false
     no_leading_underscores_for_local_identifiers: false
     prefer_single_quotes: false
     constant_identifier_names: false
     annotate_overrides: false
     overridden_fields: false
